
STORE_CSV = False
CSV_PATH = "./csv/"
PDF_PATH = "./pdf/"

# pdf miner layout analysis parameters
USE_CUSTOM_PDF_PARAMETERS = True
DEFAULT_DETECT_VERTICAL = True
DEFAULT_LINE_OVERLAP = 0.5
DEFAULT_LINE_MARGIN = 0.15
DEFAULT_WORD_MARGIN = 0.1
DEFAULT_CHAR_MARGIN = 0.5
DEFAULT_BOXES_FLOW = 0.5
